---
# yamllint disable rule:line-length
name: Lint Code Base

on: # yamllint disable-line rule:truthy rule:comments
  # allow this workflow to be called from other workflows
  workflow_call:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        if: ${{ !env.ACT }} # skip during local actions testing
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[lint,test]

      - name: Autoflake
        run: autoflake -c -r pytopas tests examples

      - name: Black
        run: black --check --diff .

      - name: isort
        run: isort -c --diff .

      - name: flake8
        run: flake8

      - name: pylint
        run: pylint .

      - name: pyupgrade
        run: |
          find -name "*.py" -print0 |\
          xargs -0 -n1 pyupgrade --py38-plus
