---
# yamllint disable rule:line-length
name: PR action

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    uses: ./.github/workflows/linter.yml

  test:
    uses: ./.github/workflows/test.yml

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        if: ${{ !env.ACT }} # skip during local actions testing

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[release]

      - name: Build
        run: make dist
